Generalize pifo oracle
calyxir/calyx pull request #2177
Opened 2024-06-25 20:25 UTC by csziklai

This PR makes progress towards #1810. It implements the python oracle for PIFOs generalized to n flows, now known as Red Robin queues. Just as with the PIFO, if a flow falls silent, the remaining flows will take their turns. That flow effectively skips its turn. To run the oracle to create a data file called "gp_test_three_flows.data" with 20 commands and a max length of 16, type in the command line

```
python3 calyx-py/calyx/queue_data_gen.py 20 16 > calyx-py/test/correctness/queues/gp_test_three_flows.data
```

and to create the corresponding expect file, run 

```
cat calyx-py/test/correctness/queues/gp_test_three_flows.data | python3 calyx-py/calyx/rrqueue_oracle.py 20 16 --keepgoing  > calyx-py/test/correctness/queues/gp_test_three_flows.expect
```

2024-06-27 12:24 UTC, anshumanmohan requested changes
Nice stuff, Cassandra!! Congratulations on really really moving the needle on our PIFOs! I have a bunch of comments for you here, but I think you will find they are all easy to understand and implement. Largely I am just trying to get your code to be future-proof and readable.

I have only reviewed one of your eDSL .py files. I don't think three of those should be merged; it's quite bad for code maintainability. Let's talk more IRL about the fix for this! But in the meantime please make fixes to that one file only; don't bother trying to massage all three files into shape. We won't need that, as I'll show you

2024-06-27 12:24 UTC, anshumanmohan commented on calyx-py/calyx/queues.py
> +   def increment_hot(self):
Nice!

2024-06-27 12:24 UTC, anshumanmohan commented on calyx-py/calyx/queues.py
> +                if self.hot == original_hot:
So now that things work, would you like to try and take out this test and see if everything still works?

2024-06-27 12:24 UTC, anshumanmohan commented on calyx-py/calyx/queues.py
> +            if self.hot == original_hot:
Same here?

2024-06-27 12:24 UTC, anshumanmohan commented on calyx-py/calyx/queues.py
> +                    return None
And here, too, you could play with removing these `self.hot == original_hot` tests

2024-06-27 12:24 UTC, anshumanmohan commented on calyx-py/test/correctness/queues/rr_queues/rr_queue.py
> +sys.path.insert(0, parentdir)
Just curious why you needed these!

2024-06-27 12:24 UTC, anshumanmohan commented on calyx-py/test/correctness/queues/rr_queues/rr_queue.py
> +def insert_pifo(
Consider renaming this method to `insert_rr_pifo`

2024-06-27 12:24 UTC, anshumanmohan commented on calyx-py/test/correctness/queues/rr_queues/rr_queue.py
> +   for num in range(len(fifos)):
Consider the more Pythonic version, `for fifo in fifos:`

2024-06-27 12:24 UTC, anshumanmohan commented on calyx-py/test/correctness/queues/rr_queues/rr_queue.py
> +       name = "queue_" + str(num)
Consider f-strings: https://www.geeksforgeeks.org/formatted-string-literals-f-strings-python/

2024-06-27 12:24 UTC, anshumanmohan commented on calyx-py/test/correctness/queues/rr_queues/rr_queue.py
> +    #    _ , flow_reg = pifo.eq_store_in_reg(val_lt_cell.out, val_gt_cell.out)
We'll want to remove these commented-out lines before merging

2024-06-27 12:24 UTC, anshumanmohan commented on calyx-py/test/correctness/queues/rr_queues/rr_queue.py
> +       handle1 = cb.if_with(pifo.le_use(value, boundaries[b+1]),
Just rename to `handle`?

2024-06-27 12:24 UTC, anshumanmohan commented on calyx-py/test/correctness/queues/rr_queues/rr_queue.py
> +   handles = []
This is a really cool list that does a lot, I think we need to (1) give it a more descriptive name, and (2) have a comment explaining what is going on! I know the answer from our conversations, but here's your chance to explain the cleverness to all!

2024-06-27 12:24 UTC, anshumanmohan commented on calyx-py/test/correctness/queues/rr_queues/rr_queue.py
> +                   cb.if_with(hot_eq_n, reset_hot, incr_hot), # are reset_hot anf incr_hot in the right order?
Stray comment

2024-06-27 12:24 UTC, anshumanmohan commented on calyx-py/test/correctness/queues/rr_queues/rr_queue.py
> +                               handles, #TODO handles is the problem?!?!
Stray comment

2024-06-27 12:24 UTC, anshumanmohan commented on calyx-py/test/correctness/queues/rr_queues/rr_queue.py
> +           ),
Nice! Minor thing to make your life easier: a new-ish thing we have begun to do is to actually create a little Pytohn handle for _all_ this logic, just called `peek_logic` for example. Then the top-level control could just become: `cb.if_with(cmd_eq_1, peek_logic)`. 

Then, we have a brand new eDSL constructor for cases. That allows us to write even more readable code. Please see the below for a taste! https://github.com/calyxir/calyx/blob/ba95ac0b1159954e5c50472e028c043c1cb555c5/calyx-py/test/correctness/queues/fifo.py#L87-L95

2024-06-27 12:25 UTC, anshumanmohan commented
At this point does this PR totally subsume https://github.com/calyxir/calyx/pull/2147? If so, please say so in the conversation of that PR, be sure to link to this PR, and close that PR! Hooray!

2024-06-27 12:29 UTC, anshumanmohan commented
In your topmatter of this PR, you give us the commands to generate .data and .expect files. Would you mind trying to put those commands into [gen_queue_data_expect.sh](https://github.com/calyxir/calyx/blob/main/calyx-py/calyx/gen_queue_data_expect.sh)? My bad, I should have done this with you much earlier and that would have saved you some copy-pasting. Better late than never!

2024-06-27 12:30 UTC, anshumanmohan commented
Also I jumped in and changed your topmatter a little: we're calling them round robin queues, not red robin! 😛

2024-06-27 16:07 UTC, csziklai commented on calyx-py/calyx/queues.py
> +       for b in range(len(self.boundaries)):
Yeah I would have but I need the actual index because I use it to index into self.data. 👍🏼

2024-06-27 16:25 UTC, csziklai commented on calyx-py/test/correctness/queues/rr_queues/rr_queue.py
> +sys.path.insert(0, parentdir)
I was failing CI, so I had to make a separate rr_queues subdirectory and then I had to find a way to import fifo.py from the directory above, so I looked it up on stack overflow.

2024-06-28 13:41 UTC, anshumanmohan commented
I jumped in and made a few changes, and I think you'd enjoy working through them a little, @csziklai! I have one very concrete request in the comments for you, since I think it will greatly improve our scalability. Please catch me IRL if you'd like to work through it together! After you have taken a stab at that, I'll jump back in and do the last few things I wanted. For now, you have control :)

2024-06-28 14:30 UTC, csziklai commented
@anshumanmohan, did you mean the thing we were talking about yesterday with factoring out the common code and importing it or the thing in the comment about the new eDSL thing for cases?

2024-07-02 17:47 UTC, anshumanmohan requested changes
Awesome job, Cassandra!! 🎉 

I jumped in and made a few more changes. I recommend you look through my commit and see what you think of them. I tried to make them discrete and easy to understand; they more or less contain one logical change each. 

I was able to massage away the value = 0 edge case. I was also able to lift a little more code into `roundrobin.py`. Take a look, I think you'll like it!

One last thing before we merge: could you please remove the directory `strict_queues` from this branch? Something like `git rm` should work. You may need a `-r` flag since it's a directory.

2024-07-02 17:59 UTC, anshumanmohan commented
Also just a heads up, I found it helpful to always run:
```
cd calyx-py/calyx/; ./gen_queue_data_expect.sh; cd -; runt -i rr_queues
```
so that I knew for sure that I was working with fresh .data and .expect files.

In case I did see errors from `runt`, I changed the command into
```
cd calyx-py/calyx/; ./gen_queue_data_expect.sh; cd -; runt -i rr_queues -d > huh.txt
```
and then examined the file `huh.txt`.

2024-07-02 19:50 UTC, anshumanmohan commented
Hooray! Now feel free to hit the big green "squash and merge" button, @csziklai!

2024-07-02 20:15 UTC, merged