Queues: PCAP-based benchmarking harness
calyxir/calyx pull request #2358
Opened 2024-11-19 21:47 UTC by polybeandip

Closes #2304

2024-11-20 04:08 UTC, polybeandip commented
Some Gantt charts from packets 1 through 20 of a PCAP (it's too big for me to upload and I forgot where I found it, sorry!)

<p align="center">
<img src="https://github.com/user-attachments/assets/2cf7ae37-7bb4-4469-bb55-37bdaa1c476c"/>
2-flow Specialized Round Robin
</p>

<p align="center">
<img src="https://github.com/user-attachments/assets/552877da-ed53-4cc3-8bc4-b04ed87e8f7e"/>
2-flow Binary Heap Round Robin
</p>

<p align="center">
<img src="https://github.com/user-attachments/assets/3ae99b21-9097-4a78-bad1-d3effce52d9a"/>
2-flow Specialized Strict
</p>

<p align="center">
<img src="https://github.com/user-attachments/assets/f6d2a22a-d0d2-4224-a1bd-550474520941"/>
2-flow Binary Heap Strict
</p>


The order packets are popped is the same (phew!), but it seems they stay in the queue much longer in the heap-based versions.

2024-12-11 19:38 UTC, anshumanmohan commented on frontends/queues/evaluation/parse_pcap.py
> +        # keep track of number of unpopped packet's
typo

2024-12-11 20:11 UTC, anshumanmohan requested changes
Thanks for all the great work, and for walking me through this IRL! Comments on Github are minimal because we spoke offline.

2024-12-11 20:11 UTC, anshumanmohan commented on fud2/scripts/calyx_py-to-calyx.rhai
> +import "calyx" as c;
@jku20 Akash has added a fud2 stage that runs `python3` on a file. This spares us from the usual pattern of:
```
python3 myfile.py | 
fud ...
```
Would you please take a look for style etc? Also we know this should have been its own PR; sorry about that!

2025-01-22 23:22 UTC, merged