Remove `rust-toolchain.toml`
calyxir/calyx pull request #2369
Opened 2024-12-04 21:53 UTC by ethanuppal

Since #2364, which added `rust-toolchain.toml`, still had failing tests on main (https://github.com/calyxir/calyx/actions/runs/12151446330/job/33886064698), I don't think this is needed?

2024-12-04 22:34 UTC, polybeandip commented
Apologies, that's my fault. Strangely, I passed CI on my branch, but failed on main; I didn't know there was a difference between those CI checks. 

I think the problem was that I forgot to remove line [`18`](https://github.com/calyxir/calyx/blob/445e1740aa36743897bfe3d163dd4f3c32c7a6b5/.github/workflows/playground.yml#L18) in [`playground.yml`](https://github.com/calyxir/calyx/blob/main/.github/workflows/playground.yml) so it ends up ignoring `rust-toolchain.toml` and grabbing the latest verison? 

I'm neutral on whether it should be removed; fine with either call

2024-12-05 01:00 UTC, ethanuppal commented
in #2365 I removed the root of the issue with a temporary hack. Not sure if we should just straight up enforce the Rust version.

2024-12-05 15:26 UTC, EclecticGriffin commented
I think it is worth keeping the toolchain toml and just fixing the line that overrides it. It's better for us to mandate a version of rust for the CI rather than have the periodic breakage when a new lint or check gets introduced, since that makes things pretty brittle and causes a fair bit of chaos.

2024-12-05 15:27 UTC, EclecticGriffin commented
This particular cycle of CI breakage is by no means the first time this has happened and is arguably attributable to not standardizing a single rust version for all of CI

2024-12-05 19:26 UTC, EclecticGriffin requested changes
We should keep the file and just ensure it is used everywhere

2024-12-05 21:48 UTC, ethanuppal commented
ok

2024-12-10 20:17 UTC, EclecticGriffin commented
Closed in favor of #2374

2024-12-10 20:17 UTC, closed without merging